import Link from "next/link";
import Head from 'next/head'

function Layout({children}:{children: React.ReactNode}) {
  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <nav className="flex sm:justify-center space-x-4 py-8">
        {[
          ['Home', '/'],
          ['Hello', '/hello'],
        ].map(([title, url], index) => (
          <Link href={url} key={index} className="rounded-lg px-3 py-2 text-slate-950 font-medium hover:bg-slate-100 hover:text-slate-950 bg-red-400">{title}</Link>
        ))}
      </nav>
      {children}
    </>
  )
}

export default Layout;